### ISSUE TITLE
Play a song in Spotify to fetch lyrics message when song playing

### ISSUE THREAD

**Issue by Markie2317** [fr31/spotifylyrics#75] opened 2018-02-22 12:11 UTC
Title says it all. Spotify is running, app does not see this. 
Tried each version, no change.
Uninstalled and reinstalled Spotify, no change.
Windows 10 64

**Comment by Ferrothrax** [comment] 2018-03-04 21:27
I get the same problem. Experienced it with both 1.14 and 1.15 this evening. It may be related to a recent Spotify update, as I can confirm SpotifyLyrics was working well last week before I restarted Spotify and it updated itself.

**Comment by Arecsu** [comment] 2018-03-04 21:36
Yeah, it is because the last update. I will check

**Comment by Arecsu** [comment] 2018-03-04 22:28
Ok, the problem of course has to do with the last update. Spotify in the previous app had the class SpotifyMainWindow, so SpotifyLyrics could identify it and get the name of the songs by the title of the window. The problem now is that the class has changed to Chrome_WidgetWin_0 (the number seems to change randomly sometimes), but this class is the same as many applications that uses the same frontend, like... Google Chrome, Visual Studio Code, uff so many apps nowdays. 

Now we need a way to identify the window by the process spotify.exe. Don't know how to make it work. WIll check

**Comment by Arecsu** [comment] 2018-03-05 00:23
GOT EM BOIS

![image](https://user-images.githubusercontent.com/12679098/36952701-27b3bb18-1ff2-11e8-8600-bbfb65aa3e49.png)

@fr31 this is really important and I still don't know how to compile that haha. Would you please release a new version? I'll upload the commit

**Comment by Arecsu** [comment] 2018-03-05 01:56
## Grab the new release with the fix from my fork here:

https://github.com/Arecsu/spotifylyrics/releases

Don't know where @fr31 is by the moment, and I've managed to compile it

**Comment by fr31** [comment] 2018-03-05 02:28
Sorry, been busy lately. I'll merge the pull request and update the releases tomorrow.

**Comment by fr31** [comment] 2018-03-05 11:13
Ok, this should be all good now. Everything merged and [released](https://github.com/fr31/spotifylyrics/releases).

**Closed by fr31** 2018-03-05 11:13 UTC
